services:
  db:
    image: postgres:15
    container_name: nest_peploy_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dars1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: nest_deploy_app
    restart: always
    env_file:
      - .env
    ports:
      - "3030:3000"
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "

volumes:
  postgres_data: